// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'event.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$EventImpl _$$EventImplFromJson(Map<String, dynamic> json) => _$EventImpl(
      eventId: json['eventId'] as int? ?? 0,
      listingStartDate: json['listingStartDate'] as String? ?? '',
      endDate: json['endDate'] as String? ?? '',
      title: json['title'] as String? ?? '',
      eventLevel: json['eventLevel'] as String? ?? '',
      eventLanguage: json['eventLanguage'] as String? ?? '',
      days: json['days'] as String? ?? '',
      weeks: json['weeks'] as String? ?? '',
      eventDelivery: json['eventDelivery'] as String? ?? '',
      courseFrequency: json['courseFrequency'] as String? ?? '',
      courseRepeatsEvery: json['courseRepeatsEvery'] as String? ?? '',
      cophortRepeatsOn: (json['cophortRepeatsOn'] as List<dynamic>?)
              ?.map((e) => e as String)
              .toList() ??
          const [],
      repeatsOn: json['repeatsOn'] as String? ?? '',
      andMonth: json['andMonth'] as String? ?? '',
      every: json['every'] as String? ?? '',
      venueName: json['venueName'] as String? ?? '',
      meetingRoomNo: json['meetingRoomNo'] as String? ?? '',
      name: json['name'] as String? ?? '',
      country: json['country'] as String? ?? '',
      address1: json['address1'] as String? ?? '',
      address2: json['address2'] as String? ?? '',
      city: json['city'] as String? ?? '',
      state: json['state'] as String? ?? '',
      postalCode: json['postalCode'] as String? ?? '',
      liveProvider: json['liveProvider'] as String? ?? '',
      accountName: json['accountName'] as String? ?? '',
      providerRegistrationRequired:
          json['providerRegistrationRequired'] as String? ?? '',
      liveMeetingId: json['liveMeetingId'] as String? ?? '',
      password: json['password'] as String? ?? '',
      pricingCategory: json['pricingCategory'] as String? ?? '',
      currency: json['currency'] as String? ?? '',
      listPrice: json['listPrice'] as String? ?? '',
      eventProviderName: json['eventProviderName'] as String? ?? '',
      providerDescription: json['providerDescription'] as String? ?? '',
      speakerName: json['speakerName'] as String? ?? '',
      speakerProfile: json['speakerProfile'] as String? ?? '',
      tagline: json['tagline'] as String? ?? '',
      briefDescription: json['briefDescription'] as String? ?? '',
      fullDescription: json['fullDescription'] as String? ?? '',
      features: json['features'] as String? ?? '',
      structureDescription: json['structureDescription'] as String? ?? '',
      benefits: json['benefits'] as String? ?? '',
      addPreRequisites: json['addPreRequisites'] as String? ?? '',
      listOfPreRequisites: json['listOfPreRequisites'] as String? ?? '',
      attendance: json['attendance'] as String? ?? '',
      quizCompletion: json['quizCompletion'] as String? ?? '',
      quizGrading: json['quizGrading'] as String? ?? '',
      assessmentCompletion: json['assessmentCompletion'] as String? ?? '',
      assessmentGrading: json['assessmentGrading'] as String? ?? '',
      sessionId: json['sessionId'] as String? ?? '',
      sessionDate: json['sessionDate'] as String? ?? '',
      startTime: json['startTime'] as String? ?? '',
      endTime: json['endTime'] as String? ?? '',
      sessionTitle: json['sessionTitle'] as String? ?? '',
      sessionDescription: json['sessionDescription'] as String? ?? '',
      sessionVenueNumber: json['sessionVenueNumber'] as String? ?? '',
      sessionInfoVenueName: json['sessionInfoVenueName'] as String? ?? '',
      sessionSpeakers: json['sessionSpeakers'] as String? ?? '',
      sessionInfoSpeakerProfile:
          json['sessionInfoSpeakerProfile'] as String? ?? '',
      speakerImage: json['speakerImage'] as String? ?? '',
      sessionInfoLiveProvider: json['sessionInfoLiveProvider'] as String? ?? '',
      registrationRequired: json['registrationRequired'] as String? ?? '',
      sessionInfoAccountName: json['sessionInfoAccountName'] as String? ?? '',
      meetingId: json['meetingId'] as String? ?? '',
      sessionInfoPassword: json['sessionInfoPassword'] as String? ?? '',
      sessionInfoTitle: json['sessionInfoTitle'] as String? ?? '',
      description: json['description'] as String? ?? '',
      contentType: json['contentType'] as String? ?? '',
      contentLink: json['contentLink'] as String? ?? '',
      contentTags: json['contentTags'] as String? ?? '',
    );

Map<String, dynamic> _$$EventImplToJson(_$EventImpl instance) =>
    <String, dynamic>{
      'eventId': instance.eventId,
      'listingStartDate': instance.listingStartDate,
      'endDate': instance.endDate,
      'title': instance.title,
      'eventLevel': instance.eventLevel,
      'eventLanguage': instance.eventLanguage,
      'days': instance.days,
      'weeks': instance.weeks,
      'eventDelivery': instance.eventDelivery,
      'courseFrequency': instance.courseFrequency,
      'courseRepeatsEvery': instance.courseRepeatsEvery,
      'cophortRepeatsOn': instance.cophortRepeatsOn,
      'repeatsOn': instance.repeatsOn,
      'andMonth': instance.andMonth,
      'every': instance.every,
      'venueName': instance.venueName,
      'meetingRoomNo': instance.meetingRoomNo,
      'name': instance.name,
      'country': instance.country,
      'address1': instance.address1,
      'address2': instance.address2,
      'city': instance.city,
      'state': instance.state,
      'postalCode': instance.postalCode,
      'liveProvider': instance.liveProvider,
      'accountName': instance.accountName,
      'providerRegistrationRequired': instance.providerRegistrationRequired,
      'liveMeetingId': instance.liveMeetingId,
      'password': instance.password,
      'pricingCategory': instance.pricingCategory,
      'currency': instance.currency,
      'listPrice': instance.listPrice,
      'eventProviderName': instance.eventProviderName,
      'providerDescription': instance.providerDescription,
      'speakerName': instance.speakerName,
      'speakerProfile': instance.speakerProfile,
      'tagline': instance.tagline,
      'briefDescription': instance.briefDescription,
      'fullDescription': instance.fullDescription,
      'features': instance.features,
      'structureDescription': instance.structureDescription,
      'benefits': instance.benefits,
      'addPreRequisites': instance.addPreRequisites,
      'listOfPreRequisites': instance.listOfPreRequisites,
      'attendance': instance.attendance,
      'quizCompletion': instance.quizCompletion,
      'quizGrading': instance.quizGrading,
      'assessmentCompletion': instance.assessmentCompletion,
      'assessmentGrading': instance.assessmentGrading,
      'sessionId': instance.sessionId,
      'sessionDate': instance.sessionDate,
      'startTime': instance.startTime,
      'endTime': instance.endTime,
      'sessionTitle': instance.sessionTitle,
      'sessionDescription': instance.sessionDescription,
      'sessionVenueNumber': instance.sessionVenueNumber,
      'sessionInfoVenueName': instance.sessionInfoVenueName,
      'sessionSpeakers': instance.sessionSpeakers,
      'sessionInfoSpeakerProfile': instance.sessionInfoSpeakerProfile,
      'speakerImage': instance.speakerImage,
      'sessionInfoLiveProvider': instance.sessionInfoLiveProvider,
      'registrationRequired': instance.registrationRequired,
      'sessionInfoAccountName': instance.sessionInfoAccountName,
      'meetingId': instance.meetingId,
      'sessionInfoPassword': instance.sessionInfoPassword,
      'sessionInfoTitle': instance.sessionInfoTitle,
      'description': instance.description,
      'contentType': instance.contentType,
      'contentLink': instance.contentLink,
      'contentTags': instance.contentTags,
    };
